
---
include:
  - board: seeeduino_xiao_ble
    shield: chalk_left 
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: chalk_right 
  - board: seeeduino_xiao_ble
    shield: settings_reset
